Revert "Run tests before install"
If Cyclone is not installed, the tests cannot find the C header files.

./cyclone unit-tests.scm && ./unit-tests
[91munit-tests.c:360:10: fatal error: cyclone/types.h: No such file or directory
360 | #include "cyclone/types.h"

This reverts commit 341e1a269732a14c87d03d136d6390c26ba8e7a6.